import { Detalles } from './detalles.model';
import { Localidad } from './localidad.model';
import { Usuario } from './usuario.model';
// Generated by https://quicktype.io

export class Avisos {
	constructor(
		public ok: boolean,
		public mensaje: string,
		public avisos: Aviso[],
		public total: number
	) { }
}

export class Aviso {
	constructor(
		public _id?: string,
		public imgs?: string[],
		public calle?: string,
		public altura?: number,
		public piso?: number,
		public depto?: string,
		public titulo?: string,
		public descripcion?: string,
		public precio?: number,
		public tipocambio?: string,
		public publicarprecio?: boolean,
		public aptocredito?: boolean,
		public codigopostal?: string,
		public activo?: boolean,
		public destacado?: boolean,

		public tipooperacion?: TipoOperacion,
		public tipoinmueble?: TipoInmueble,
		public tipounidad?: TipoUnidad,
		public localidad?: Localidad,
		public coords?: {
			lat?: string,
			lng?: string
		},

		public usuario?: Usuario,
		public detalles?: Detalles,
		// el usuario se adjunta en el controlador de avisos en el backend,
		// lo obtiene el middleware auth cuando verifica el token
		// public inmobiliaria?: Inmobiliaria,
		public __v?: number
	) {
		this.imgs = [];
	}
}

export class TiposOperaciones {
	constructor(
		public ok: boolean,
		public operaciones: TipoOperacion[],
		public total: number,
	) { }
}

export class TipoOperacion {
	constructor(
		public _id: string,
		public nombre: string,
		public id: string
	) { }
}

export class TiposInmuebles {
	constructor(
		public ok: boolean,
		public inmuebles: TipoInmueble[],
		public total: number,
	) { }
}

export class TipoInmueble {
	constructor(
		public _id: string,
		public nombre: string,
		public id: string
	) { }
}

export class TiposUnidades {
	constructor(
		public ok: boolean,
		public unidades: TipoUnidad[],
		public total: number,
	) { }
}

export class TipoUnidad {
	constructor(
		public _id: string,
		public nombre: string,
		public id: string,
		public idparent: string
	) { }
}

export class OpcionesDormitorios {
	constructor(
		public ok: boolean,
		public opciones: OpcionDormitorios[],
		public total: number,
	) { }
}

export class OpcionDormitorios {
	constructor(
		public _id: string,
		public nombre: string,
		public id: string
	) { }
}