// Generated by https://quicktype.io

export class DetallesResp {
  constructor(
    public ok: boolean,
    public mensaje: string,
    public detalles: Detalles[],
    public total: number
  ) { }
}

export class Detalles {
  constructor(
    public terraza?: string,

    // el usuario se adjunta en el controlador de propiedades en el backend,
    // lo obtiene el middleware auth cuando verifica el token
    // public inmobiliaria?: Inmobiliaria,
    public _id?: string,
    public __v?: number
  ) { }
}

interface Inmobiliaria {
  _id: string;
  nombre: string;
  usuario: string;
  __v: number;
  img: string;
}

interface Usuario {
  img: string;
  _id: string;
  email: string;
  nombre: string;
}
