import { Detalles } from './detalle.model';

// Generated by https://quicktype.io

export class Propiedades {
  constructor(
    public ok: boolean,
    public mensaje: string,
    public propiedades: Propiedad[],
    public total: number
  ) { }
}

export class Propiedad {
  constructor(
    public calle?: string,
    public altura?: number,
    public piso?: number,
    public depto?: string,
    public tipoinmueble?: string,
    public tipounidad?: string,
    public tipooperacion?: string,
    public titulo?: string,
    public descripcion?: string,
    public precio?: number,
    public moneda?: string,
    public nopublicarprecio?: boolean,
    public aptocredito?: boolean,
    public pais?: string,
    public provincia?: string,
    public partido?: string,
    public localidad?: string,
    public barrio?: string,
    public subbarrio?: string,
    public codigopostal?: string,
    public usuario?: Usuario,
    public detalles?: Detalles,
    // el usuario se adjunta en el controlador de propiedades en el backend,
    // lo obtiene el middleware auth cuando verifica el token
    // public inmobiliaria?: Inmobiliaria,
    public imgs?: string[],
    public _id?: string,
    public __v?: number
  ) {
    this.imgs = [];
  }
}

interface Inmobiliaria {
  _id: string;
  nombre: string;
  usuario: string;
  __v: number;
  img: string;
}

interface Usuario {
  img: string;
  _id: string;
  email: string;
  nombre: string;
}
